### ISSUE TITLE
Move Persistence Buttons and Prompts to Vue.js (Ohm Playgrounds)

### ISSUE THREAD

**Issue by mroeder** [harc/ohm-editor#15]
Ohm Playgrounds was built on the old architecture for the Ohm visualizer/editor. Move things to Vue.js for better modularization.

**Comment by mroeder** [comment]
@pdubroy started here 2df1a7bfeaa5e41324e80272865cd96d696158fb.
Let me know what you think!

**Comment by pdubroy** [comment]
Overall looks great -- didn't take long for you to figure out Vue.js I see :-) I suggested a few changes on the commit itself.

**Comment by mroeder** [comment]
Well, unfortunately it did. It took me a day to figure it out and do it. Time I would have liked to spend differently. :-(
