### ISSUE TITLE
Editor scroll bar overlaps GitHub login box

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm-editor#17]
I discovered this by accident today...if the grammar is long enough for a scroll bar to appear, then when the GitHub login box appears, it is (for some weird reason) rendered above the login box:

![screen shot 2017-01-10 at 5 22 51 pm](https://cloud.githubusercontent.com/assets/17293/21814428/8f698a68-d759-11e6-9af1-43d4a31b0265.png)

Marko, can you take a look?

**Comment by mroeder** [comment]
This bar should generally not be visible and somehow Chrome is buggy and showing it sometimes.
However, I will try to get the prompt above all.

**Comment by mroeder** [comment]
Set the `z-index` to the highest currently used. That solve the problem if I have "always show scrollbars" on.
