### ISSUE TITLE
Support multiple grammars in the same file

### ISSUE THREAD

**Issue by rtoal** [harc/ohm-editor#25]
Looks like the Ohm editor cares more about the first grammar than the subgrammar (see attached image).
<img width="755" alt="screen shot 2017-02-07 at 6 58 10 pm" src="https://cloud.githubusercontent.com/assets/538615/22721775/96c8e9ba-ed67-11e6-848f-423e055e0d95.png">

**Comment by mroeder** [comment]
Currently, multiple grammars are not supported inside the Ohm editor. Unfortunately, this means that you also cannot create a subgrammar either.
It used to be that you would see an error in the grammar pane when there was more than one grammar in it but it looks like it is a little more "robust" now and accepting everything, if valid, but only using the first grammar.

**Comment by pdubroy** [comment]
Ray, thanks for filing this. The only thing I'll add to what Marko said is that I'd be happy if we fixed this. I think it shouldn't be too hard -- now that examples have start rules associated with them, we could just use `<optgroup>` to put the rules from both grammars into the start rule dropdown. E.g.:

<img width="220" alt="screen shot 2017-02-12 at 2 28 07 pm" src="https://cloud.githubusercontent.com/assets/17293/22862481/9c1ec846-f12f-11e6-9272-70eedd7cd058.png">

**Comment by rtoal** [comment]
Any progress on this?

**Comment by pdubroy** [comment]
I'm working on this. It turned out to be a bit more complicated than I thought!

A screenshot from what I have so far:

<img width="343" alt="Screen Shot 2021-11-20 at 16 10 57" src="https://user-images.githubusercontent.com/17293/142731499-b7f38299-fe54-4c34-951e-5b7fbbc2f4ae.png">

**Comment by pdubroy** [comment]
Support has landed on master. I'll keep this issue open until the remaining things are fixed:
- [ ] Fix 'peek:ruleDefinition' to look at the correct grammar
- [ ] Fix rule hyperlinks
- [ ] (Maybe) automatically set the selected grammar when adding a new example (if there are grammars)

**Comment by pdubroy** [comment]
This is now fixed and deployed on https://ohmlang.github.io/editor.
