### ISSUE TITLE
This short grammar doesn't work... Probably user error.

### ISSUE THREAD

**Issue by daveloyall** [harc/ohm-editor#32]
lamcalc {
    
    expr
    	= variable
    	| "λ" variable "." expr
    	| "(" expr expr ")"
    
    variable
    	= letter*
    
    }

...gives: `Rule expr involves an alternation which has inconsistent arity (expected 1, got 4)` on first line that contains a `|`.

**Comment by alexwarth** [comment]
Hi Dave,

You should read through the math tutorial / demo, which has a really good
explanation of arities, etc.:
https://github.com/harc/ohm/blob/master/examples/math/index.html

There's also a good explanation in Sec. 2.3 of this paper:
https://ohmlang.github.io/pubs/dls2016/modular-semantic-actions.pdf

Cheers,
Alex

**Comment by bmavity** [comment]
The short answer is that you can fix it by adding a name at the end of each clause

`expr
	= variable                     -- variable
	| "λ" variable "." expr  -- variableWithExpression
	| "(" expr expr ")"       -- expressionWithParens
`


The long answer is in the comments here:
https://github.com/harc/ohm/blob/482b6937781a2f1b7d752df7dbaf9d4367738210/examples/math/index.html#L180

**Comment by daveloyall** [comment]
Thanks, you two!

**Comment by al6x** [comment]
This is terrible idea. I made the grammar rules in about 30 min. But already spent 4 hours to make the semantic rules work and still can't, it's extremely hard to work with.
