### ISSUE TITLE
Wishlist: Add metaprogramming capabilities

### ISSUE THREAD

**Issue by asrp** [harc/ohm-editor#33]
I'm not sure if this is even remotely the direction in which the Ohm editor is intended to go but it'd be nice to be able to do metaprogramming.

That is, have an example input3 written in a grammar grammar3 itself written in grammar2 itself written in grammar1 and grammar1 written in Ohm. And then be able to visualize how grammar3 parses input3.

**Comment by pdubroy** [comment]
Thanks for the suggestion, but I'd prefer to keep the core editor simple, and I don't think enough people would use this to make it worth supporting.
