### ISSUE TITLE
Install / Run Issue

### ISSUE THREAD

**Issue by darth-cheney** [harc/ohm-editor#38]
I'm able to get the basics installed when following modified yarn install instructions from #37 . However when I run `npm start` I get the following error (the web app loads but grammars are not parsed):
```
Error: ENOENT: no such file or directory, stat '/home/ecgade/projects/ohm-editor/ohm-editor/node_modules/ohm-js/dist/ohm.min.js'
```
If I look inside my node_modules folder I see that the path to `dist/ohm.min.js` is not what the output is looking for (`node_modules/ohm-js/dist`) but actually `node_modules/ohm-js/ohm-js/dist`. In other words, there's a nested directory also called ohm-js in the current versions of ohm. 
  
I am not sure where this error is "coming from" so I don't know where to possibly change code.

**Comment by pdubroy** [comment]
Thanks for reporting. As you can see, we haven't touched this repo in quite a while. The first thing I would try is to point the package.json to the latest released version of Ohm. For some reason, it is currently using a specific Git revision, rather than using the latest release version.

**Comment by pdubroy** [comment]
This should be fixed now. At least, everything works for me. Please feel free to re-open if you are still seeing problems.
