### ISSUE TITLE
Incorrect styling of some failed expressions

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm-editor#5]
Here's a screenshot from the latest version:

<img width="115" alt="screen shot 2016-11-18 at 7 58 01 pm" src="https://cloud.githubusercontent.com/assets/17293/20442877/bd13ac54-adca-11e6-927c-2a9fa4f12442.png">

This is with the arithmetic grammar, and the input `1+2*3-`. Here's what it should look like:

<img width="110" alt="screen shot 2016-11-18 at 8 11 36 pm" src="https://cloud.githubusercontent.com/assets/17293/20443272/7d47b7b2-adcc-11e6-9aff-a8675c40c14e.png">

Note a couple of problems:

- The top-level `Exp` succeeded, why is it pink?
- `AddExp_plus`, `AddExp_minus`, and `MulExp` are missing the disclosure arrows (this is probably related to `vbox`/`isInVBox`)

**Comment by pdubroy** [comment]
Also, I noticed that we no longer have the `[Grow LR]` expression.

**Comment by lilyx** [comment]
Solved by 0edb5f9dd84c08845f60063c08bf5e2532c66fa6
