### ISSUE TITLE
Can't save grammar into localstorage due to exception

### ISSUE THREAD

**Issue by pdubroy** [harc/ohm-editor#6]
When I edit the grammar and replace it with a new one (e.g., replacing the arithmetic grammar with `G { Start = letter* }`, I see the following exception in the console:

![screen shot 2016-12-01 at 11 24 35 am](https://cloud.githubusercontent.com/assets/17293/20790511/f359f3e8-b7b8-11e6-9ad6-64f8dc5cbdf4.png)

This seems to make it impossible to save the grammar to localstorage. When I reload the page, my grammar edits are always gone, and my grammar is replaced with the arithmetic grammar again.

**Comment by pdubroy** [comment]
@sakekasi I think this has been going on for a while. Can you look into this?

**Comment by pdubroy** [comment]
@sakekasi, any update on this?

**Comment by mroeder** [comment]
I think I might have fixed it along the way with the playgrounds... I will reconfirm.

**Comment by mroeder** [comment]
Still an issue @sakekasi. However, the issue only occurs when there is an example that has a start rule attached (e.g. in the stack trace above there was an example that had `Exp` as start rule).

**Comment by sakekasi** [comment]
@mroeder @pdubroy I'm on it

**Comment by pdubroy** [comment]
Original issue seems to be fixed.
