### ISSUE TITLE
Ohm-Editor vs '...' syntax

### ISSUE THREAD

**Issue by guitarvydas** [harc/ohm-editor#72]
AFAICT the '...' syntax is not working in https://ohmjs.org/editor/ (on Safari and Chrome).

("not working" means - no error messages, no parse, parse tree grayed out (hanging?))

test grammar:
basic {
  Main = Token
  Token = "a"
}

child1 <: basic {
  Child1Token = "a"
  Token += Child1Token
}

child2a <: basic {
  Child2aToken = "a"
  Token := ... | Child2aToken
}

child2b <: basic {
  Child2bToken = "a"
  Token := Child2bToken | ...
}

test text:
a

the above seems to work from the command line
(refreshing the web page does not seem to change the behaviour of the editor, though)

**Comment by pdubroy** [comment]
Just release Ohm v16.3.2 which fixes the issue:

<img width="554" alt="CleanShot 2022-03-23 at 12 13 13@2x" src="https://user-images.githubusercontent.com/17293/159686935-5b804f76-07f0-4dc2-8a2e-93bb8ba98611.png">
